# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

DEFAULT_USER=Vyndrix
prompt_context(){}

source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
antidote load

export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

DEV_DIR=$HOME/Developer

alias dev="cd $DEV_DIR"
alias dot="cd $DEV_DIR/dotfiles"
alias ws="cd $DEV_DIR/vyndrix.me"
alias gemi="gemini --sandbox"
alias ai:ga="cd ~/.agents"
alias ai:gs="cd ~/.agents/skills"

# Consider moving this into a dedicated file
repos:ssh() {
  NAME=""
  if ! [[ -z "$1" ]]; then
    NAME=$1
  fi

  gh repo list --json sshUrl --jq '.[] | .sshUrl | select(. | contains("'$NAME'"))'
}

# TODO: move this into a separate branch. It is a android specific config.
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_NDK=$ANDROID_HOME/ndk/26.1.10909125
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"

doppler run --mount s.env -- cat s.env > ~/.doppler/s.env;
source ~/.doppler/s.env;
rm -rf ~/.doppler/s.env;

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

eval "$(direnv hook zsh)"
